version: "3.9"

services:
  # SQL Server
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver2022
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Root@12345
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql
    restart: unless-stopped

  # Redis (para cache)
  redis:
    image: redis:7-alpine
    container_name: redis-cache
    command: ["redis-server", "--requirepass", "devpassword123"]
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    restart: unless-stopped

  # RabbitMQ (mensageria)
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"     # Porta de comunicação da aplicação
      - "15672:15672"   # Painel de administração
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    restart: unless-stopped

volumes:
  sqlserverdata:
  redisdata:
  rabbitmqdata:
